Repository wso2/ballerina-integrator, pull requests merged in 2019-07, with the labels that each got.

#64 Add tests for healthcare service
  examples/guides/services/healthcare-service/tests/clemency-hospital-service-test.bal
  examples/guides/services/healthcare-service/tests/grand-oak-hospital-service-test.bal
  examples/guides/services/healthcare-service/tests/healthcare-service-test.bal
Labels: Priority/High, Severity/Critical, Type/Test

#105 Modify message broadcast guide
  examples/guides/messaging/message-broadcasting/README.md
  examples/guides/messaging/message-broadcasting/guide/appointment_processor_one.bal
  examples/guides/messaging/message-broadcasting/guide/appointment_processor_two.bal
  examples/guides/messaging/message-broadcasting/guide/database_writer.bal
  examples/guides/messaging/message-broadcasting/guide/file_writer.bal
  examples/guides/messaging/message-broadcasting/resources/database_script.sql
  examples/guides/messaging/message-broadcasting/resources/input.json
  examples/guides/messaging/message-broadcasting/resources/message_broadcasting.svg
  examples/guides/messaging/message-broadcasting/resources/message_broadcasting_guide.svg
Labels: Type/Docs

#122 Improve message processor
  connectors/module-messageStore/messageStore/message_processor_task.bal
  connectors/module-messageStore/messageStore/message_store_endpoint.bal
Labels: Priority/High, Severity/Major, enhancement
